config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  #get 'home/index'
  root 'home#index'
  get 'home/about'

  post "/" => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
    validates :ticker, presence: true
    validates :ticker, format: { without: /\s/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    @api = StockQuote::Stock.new(api_key: "pk_0ad01f64792b4f469d89b4bb6b8d1ca4")
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @api = StockQuote::Stock.new(api_key: "pk_0ad01f64792b4f469d89b4bb6b8d1ca4")
    if params[:ticker] == ""
      @nothing = "Hey! You forgot to Enter a Symbol"
    elsif params[:ticker]
      @stock = StockQuote::Stock.quote(params[:ticker])
      
    end
  end

  def about
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # 
  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not authorized to edit this stock" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissable" role="alert">
  <button type="button" class="close" data-dismiss="alert">
    <small><sup>X</sup></small>
  </button>
  <%= content_tag(:div, msg) %>
</div>
<% end %>

app/views/home/_footer.html.erb
<center> Copyright (c) Arazaki</center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Stocking App", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About", home_about_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Show Stocks", stocks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Stock", new_stock_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>

      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>
<p>Hello, Fabio here</p>

app/views/home/index.html.erb
<h1>Stocking</h1>
<%= form_tag root_path, :method => "POST" do %>
  <%= text_field_tag "ticker", nil, placeholder: "Enter Ticker Symbol", size: 50 %>
  <%= submit_tag "Lookup" %>
<% end %>

<% if @stock %>
  <%= @stock.inspect %>
  $<%= @stock.latest_price %>
<% elsif @nothing %>
  <%= @nothing %>
<% end %>
<% if @error %>
  <%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby Stock App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    
    <%= render 'home/navbar' %>
    <div class="container">
    <%= render 'home/flash' %>

      <br/>
      <br/>
      <%= yield %>
    </div>
    <%= render 'home/footer' %>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<table class="table table-striped table-hover table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Company</th>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Market Cap</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <% if stock.user_id == current_user.id %>
      <!-- Must handle the error if the @ticker is not found
      -> best place to handle is while creating a new ticker. If the string passed is not valid (ticker not found, the error must be handled)
       -->
        <% @ticker = StockQuote::Stock.quote(stock.ticker) %>
        <% if !@ticker %>
          <tr>
            <td><%= link_to "Error", stock %></td>
            <td><%= stock.ticker %></td>
            <td>N/A</td>
            <td>N/A</td>
            <td><center><%= link_to "Edit", edit_stock_path(stock) %></center></td>
            <td><center><%= link_to "Delete", stock, method: :delete, data: { confirm: "Are you sure?" } %></center></td>
          </tr>
        <% else %>
          <tr>
            <td><%= link_to @ticker.company_name, stock %></td>
            <td><%= @ticker.symbol %></td>
            <td><%= number_to_currency(@ticker.latest_price, :precision => 2, :delimeter => ',') %></td>
            <td><%= number_to_currency(@ticker.market_cap, :precision => 0, :delimeter => ',') %></td>
            <td><center><%= link_to "Edit", edit_stock_path(stock) %></center></td>
            <td><center><%= link_to "Delete", stock, method: :delete, data: { confirm: "Are you sure?" } %></center></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Stock", new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<% @ticker = StockQuote::Stock.quote(@stock.ticker) %>
  <% if !@ticker %>
    The ticker: <%= stock.ticker %> does not exist!
      <br />
  <% else %>
    <strong><%= @ticker.company_name %></strong><br />
    Ticker symbol: <%= @ticker.symbol %><br />
    Current price: <%= number_to_currency(@ticker.latest_price, :precision => 2, :delimeter => ',') %><br />
    Previous close: <%= number_to_currency(@ticker.previous_close, :precision => 2, :delimeter => ',') %><br />
    Percent change: <%= number_to_percentage(@ticker.change_percent, :precision => 2, :delimeter => ',') %><br />
    YTD change: <%= number_to_percentage(@ticker.ytd_change, :precision => 2, :delimeter => ',') %><br />
    Market Cap: <%= number_to_currency(@ticker.market_cap, :precision => 0, :delimeter => ',') %><br />
    
  <% end %>
<p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>